### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by ghost** [zrq0123/BiXGBoost#1]
学长你好， 我最近在拜读你的一片论文，BiXGBoost: a scalable, flexible boosting based method for
reconstructing gene regulatory networks.论文中用到了Escherichia coli network这个数据集。恕我愚钝，不知道怎么收集到完整的数据。希望你可以帮助。

安好！

**Comment by zrq0123** [comment]
Hi, the expression data is from GSE20305, including cold, heat and oxidative stress conditions.  The gold standard network is derived from DREAM5 challenge Network 3 and RegulonDB. The genes not in GSE20305 should be filtered.

**Comment by ghost** [comment]
Hello, thank for you reply. Now I hava the expression data, then I  sought the gold standard network in  DREAM5 challenge Network 3 and RegulonDB,but did not find.
Thank you again for your help.

**Comment by zrq0123** [comment]
Sorry for late, I have uploaded the required datasets

**Comment by ghost** [comment]
It's really nice of you to provide the  gold standard network. Can I have your contact information, such as Wechat?

**Comment by zrq0123** [comment]
Of course, leave your email, then I'll send my Wechat to you.

**Comment by ghost** [comment]
Thanks, fmk_0817@qq.com
